"""Added Account Order Tables

Revision ID: 724fbe4caaea
Revises: 10471062a668
Create Date: 2024-05-18 10:55:12.151061

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from app.models.order import EncryptedFloat

# revision identifiers, used by Alembic.
revision = '724fbe4caaea'
down_revision = 'a043c9edc9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('available_money', EncryptedFloat(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('tickets_bought', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('account')
    # ### end Alembic commands ###
